function [trl,trl_list] = sipWoi(cfg)

% sip_woi function create the list of events and its assciated trl matrix
% to be used in fieldtrip. It taks as an input a struct containing at leat
% the following fields:
%
% header:   header sruct generated by fieldtrip
% cue_dur:  cue duration in sec (default 5s)
% events:   reference events. The list will conta these events and the 
%           intervals between them.
% min_dur:  minimum duration in sec of a interval to be considered in the 
%           list. (default = 1s)
% beh:      struct contaning the sip behavior


cfg.srate = cfg.header.Fs;

if ~isfield(cfg,'cue_dur')
    cfg.cue_dur = 5;
end
if ~isfield(cfg,'events')
    cfg.events  = {'lick','headent'};
end
if ~isfield(cfg,'min_dur')
    cfg.min_dur = 1;
end

cue_start = cfg.beh.cue_on;

% configuration to analyze the ~3min interval before session start
pre_sess_trl    = [cfg.beh.start cue_start(1)];
pre_sess_id     = 0;
pre_sess_lab    = {'pre_sess'};
pre_sess_trl_id = 1;
nwoi_pre_sess   = 1;

% configuration to analyze interval before cue delivery (i.e. in the
% previous ITI)
pre_cue         = cue_start - cfg.cue_dur;
pre_cue_trl     = [pre_cue; cue_start]';
pre_cue_id      = -1 * ones(length(cue_start),1);
pre_cue_lab     = repmat({'pre_cue'},length(cue_start),1);
pre_cue_trl_id  = (1:length(cue_start))';
nwoi_pre_cue    = ones(length(cue_start),1);

% configuration to analyze cue intervals
cue_end     = cue_start + cfg.cue_dur;
cue_trl     = [cue_start; cue_end]';
cue_id      = ones(length(cue_start),1);
cue_lab     = repmat({'cue'},length(cue_start),1);
cue_trl_id  = (1:length(cue_start))';
nwoi_cue    = ones(length(cue_start),1);

% configuration to analyze the inter-cue-intervals (a.k.a ITI)
ici_trl     = [cue_trl(:,2) [cue_trl(2:end,1); cfg.beh.end]];
ici_id      = 2 * ones(length(cue_start),1);
ici_lab     = repmat({'ici'},length(cue_start),1);
ici_trl_id  = (1:length(cue_start))';
nwoi_ici    = ones(length(cue_start),1);

% configuration to analyze each requested event
ev_trl = [];
ev_id  = [];
ev_lab = {};
for ievent = 1:length(cfg.events)
    ev_start  = cfg.beh.([cfg.events{ievent} '_on']);
    ev_end    = ev_start + cfg.beh.([cfg.events{ievent} '_dur']);
    ev_trl    = cat(1,ev_trl, [ev_start; ev_end]');
    ev_id     = cat(1,ev_id, (ievent + 2) * ones(length(ev_start),1));
    ev_lab    = cat(1,ev_lab,repmat(cfg.events(ievent),length(ev_start),1));
end

%%%%%%% extract the trial which each event happened on %%%%%%%%%%%%%%%%%%%%
if ~isempty(ev_trl)
    [~,~,ev_trl_id] = histcounts(ev_trl(:,1),[cfg.beh.cue_on cfg.beh.end]);
    nwoi_ev = nan(size(ev_trl_id));
    for id = unique(ev_id)'
        for itr = unique(ev_trl_id(ev_id == id))'
            ev_flags = ev_id == id & ev_trl_id == itr;
            nwoi_ev(ev_flags) = 1:sum(ev_flags);
        end
    end
else
    ev_trl_id = [];
    nwoi_ev   = [];
end
%%%%%%% extract the trial which each event happened on %%%%%%%%%%%%%%%%%%%%

all_trl   = [pre_sess_trl;pre_cue_trl;cue_trl;ici_trl;ev_trl] * 1e6; % originally the timestamps were on microseconds ;
duration  = diff(all_trl,1,2);
all_ids   = [pre_sess_id;pre_cue_id;cue_id;ici_id;ev_id];
woi_label = [pre_sess_lab;pre_cue_lab;cue_lab;ici_lab;ev_lab];
trial_id  = [pre_sess_trl_id;pre_cue_trl_id;cue_trl_id;ici_trl_id;ev_trl_id];
nwoi_tr   = [nwoi_pre_sess;nwoi_pre_cue;nwoi_cue;nwoi_ici;nwoi_ev];

samples   = (all_trl - double(cfg.header.FirstTimeStamp))./cfg.header.TimeStampPerSample + 1;
tab_data  = [all_trl round(samples) duration all_ids trial_id nwoi_tr];
trl_list  = array2table(tab_data,"VariableNames",...
    {'t_start','t_end','sample_start','sample_end','duration','woi_id','trial_id','nwoi_tr'});
trl_list = addvars(trl_list,woi_label);

%%%%%%%%%%%%%%%%%%%%%%%%%%%% extract inter-woi intervals %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
woi_flags   = trl_list.woi_id == 1 | trl_list.woi_id > 2;
woi_label   = cell([],1);
iwi_trl     = [];
iwi_id      = [];
iwi_trl_id  = [];
nwoi_iwi    = [];

for itrial = 1:length(cue_start)

    ici_data    = trl_list(trial_id == itrial & trl_list.woi_id == 2,:);
    trial_data  = trl_list(trial_id == itrial & woi_flags,:);
    trial_data   = sortrows(trial_data(trial_data.trial_id == itrial,:),'t_start');

    if height(trial_data) > 1
        temp_labels = cat(2,trial_data.woi_label(1:end - 1), trial_data.woi_label(2:end));

        for ilabel = 1:size(temp_labels,1)
            woi_label = cat(1,woi_label,strcat(temp_labels{ilabel,1},'_',temp_labels{ilabel,2}));
        end

        trial_iwi   = [trial_data.t_end [trial_data.t_start(2:end); ici_data.t_end]];
        woi_label  = cat(1,woi_label,strcat(trial_data.woi_label(end),'_cue'));

        iwi_trl     = cat(1,iwi_trl,trial_iwi);
        iwi_id      = cat(1,iwi_id,zeros(size(trial_iwi,1),1));
        iwi_trl_id  = cat(1,iwi_trl_id,itrial * ones(size(trial_iwi,1),1));
        nwoi_iwi    = cat(1,nwoi_iwi,(1:size(trial_iwi,1))');
    end

end
%%%%%%%%%%%%%%%%%%%%%%%%%%%% extract inter-woi intervals %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
all_trl   = [all_trl; iwi_trl];
trl       = [all_trl zeros(size(all_trl,1),1)]; 
if ~isempty(iwi_trl)
    duration  = diff(iwi_trl,1,2);
    samples   = (iwi_trl - double(cfg.header.FirstTimeStamp))./cfg.header.TimeStampPerSample + 1;
    iwi_data  = [iwi_trl round(samples) duration iwi_id iwi_trl_id nwoi_iwi];
    iwi_list  = array2table(iwi_data,"VariableNames",...
        {'t_start','t_end','sample_start','sample_end','duration','woi_id','trial_id','nwoi_tr'});
    iwi_list = addvars(iwi_list,woi_label);
    trl_list = [trl_list;iwi_list]; % add inter-woi intervals
end

short_times             = trl_list.duration < cfg.min_dur * 1e6;
trl_list(short_times,:) = [];
trl(short_times,:)      = [];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% select specific wois %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if isfield(cfg,'woi')
    switch cfg.woi
        case {'pre_cue','cue','lick','headent','ici'}
            trl      = trl(strcmp(trl_list.woi_label,cfg.woi),:);
            trl_list = trl_list(strcmp(trl_list.woi_label,cfg.woi),:);
            
        case 'event'
            trl      = trl(trl_list.woi_id > 2,:);
            trl_list = trl_list(trl_list.woi_id > 2,:);
        case 'iwi'
            trl       = trl(trl_list.woi_id == 0,:);
            trl_list  = trl_list(trl_list.woi_id == 0,:);
    end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% select specific wois %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%




