function [trl,trlList] = sipWoi(cfg)

% sipWoi function create the list of events and its assciated trl matrix
% to be used in fieldtrip. It taks as an input a struct containing at leat
% the following fields:
%
% header:   header sruct generated by fieldtrip
% cueDur:   cue duration in sec (default 5s)
% events:   reference events. The list will conta these events and the 
%           intervals between them.
% minDur:   minimum duration in sec of a interval to be considered in the 
%           list. (default = 1s)
% beh:      struct contaning the sip behavior


cfg.srate = cfg.header.Fs;

if ~isfield(cfg,'cueDur')
    cfg.cueDuration = 5;
end
if ~isfield(cfg,'events')
    cfg.events  = {'lick','headEntry'};
end
if ~isfield(cfg,'minDur')
    cfg.minDuration = 1;
end

cueStart = cfg.beh.cueOn;

% configuration to analyze the ~3min interval before session start
preSessTrl    = [cfg.beh.startTime cueStart(1)];
preSessId     = 0;
preSessLab    = {'preSession'};
preSessTrlId  = 1;
nwoiPreSess   = 1;

% configuration to analyze interval before cue delivery (i.e. in the
% previous ITI)
preCue        = cueStart - cfg.cueDuration;
preCueTrl     = [preCue; cueStart]';
preCueId      = -1 * ones(length(cueStart),1);
preCueLab     = repmat({'preCue'},length(cueStart),1);
preCueTrlId   = (1:length(cueStart))';
nwoiPreCue    = ones(length(cueStart),1);

% configuration to analyze cue intervals
cueEnd     = cueStart + cfg.cueDuration;
cueTrl     = [cueStart; cueEnd]';
cueId      = ones(length(cueStart),1);
cueLab     = repmat({'cue'},length(cueStart),1);
cueTrlId   = (1:length(cueStart))';
nwoiCue    = ones(length(cueStart),1);

% configuration to analyze the inter-cue-intervals (a.k.a ITI)
iciTrl     = [cueTrl(:,2) [cueTrl(2:end,1); cfg.beh.endTime]];
iciId      = 2 * ones(length(cueStart),1);
iciLab     = repmat({'ici'},length(cueStart),1);
iciTrlId   = (1:length(cueStart))';
nwoiIci    = ones(length(cueStart),1);

% configuration to analyze each requested event
evTrl = [];
evId  = [];
evLab = {};
for ievent = 1:length(cfg.events)
    evStart  = cfg.beh.([cfg.events{ievent} 'On']);
    evEnd    = evStart + cfg.beh.([cfg.events{ievent} 'Duration']);
    evTrl    = cat(1,evTrl, [evStart evEnd]);
    evId     = cat(1,evId, (ievent + 2) * ones(length(evStart),1));
    evLab    = cat(1,evLab,repmat(cfg.events(ievent),length(evStart),1));
end

%%%%%%% extract the trial which each event happened on %%%%%%%%%%%%%%%%%%%%
if ~isempty(evTrl)
    [~,~,evTrlId] = histcounts(evTrl(:,1),[cfg.beh.cueOn cfg.beh.endTime]);
    nwoiEv = nan(size(evTrlId));
    for id = unique(evId)'
        for itr = unique(evTrlId(evId == id))'
            evFlags = evId == id & evTrlId == itr;
            nwoiEv(evFlags) = 1:sum(evFlags);
        end
    end
else
    evTrlId = [];
    nwoiEv  = [];
end
%%%%%%% extract the trial which each event happened on %%%%%%%%%%%%%%%%%%%%

allTrl    = [preSessTrl;preCueTrl;cueTrl;iciTrl;evTrl] * 1e6; % originally the timestamps were on microseconds ;
duration  = diff(allTrl,1,2);
allIds    = [preSessId;preCueId;cueId;iciId;evId];
woiLabel  = [preSessLab;preCueLab;cueLab;iciLab;evLab];
trialId   = [preSessTrlId;preCueTrlId;cueTrlId;iciTrlId;evTrlId];
nwoiTr    = [nwoiPreSess;nwoiPreCue;nwoiCue;nwoiIci;nwoiEv];

samples   = (allTrl - double(cfg.header.FirstTimeStamp))./cfg.header.TimeStampPerSample + 1;
tabData   = [allTrl round(samples) duration allIds trialId nwoiTr];
trlList   = array2table(tabData,"VariableNames",...
    {'timeStart','timeEnd','sampleStart','sampleEnd','duration','woiID','trialID','nWoiTrial'});
trlList = addvars(trlList,woiLabel,'NewVariableNames','woiLabel');

%%%%%%%%%%%%%%%%%%%%%%%%%%%% extract inter-woi intervals %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
woiFlags   = trlList.woiID == 1 | trlList.woiID > 2;
iwiLabel   = cell([],1);
iwiTrl     = [];
iwiId      = [];
iwiTrlId   = [];
nwoiIwi    = [];

for itrial = 1:length(cueStart)

    iciData    = trlList(trialId == itrial & trlList.woiID == 2,:);
    trialData  = trlList(trialId == itrial & woiFlags,:);
    trialData  = sortrows(trialData(trialData.trialID == itrial,:),'timeStart');

    if height(trialData) > 1
        tempLabels = cat(2,trialData.woiLabel(1:end - 1), trialData.woiLabel(2:end));

        for ilabel = 1:size(tempLabels,1)
            iwiLabel = cat(1,iwiLabel,strcat(tempLabels{ilabel,1},'_',tempLabels{ilabel,2}));
        end

        trialIwi   = [trialData.timeEnd [trialData.timeStart(2:end); iciData.timeEnd]];
        iwiLabel   = cat(1,iwiLabel,strcat(trialData.woiLabel(end),'_cue'));

        iwiTrl     = cat(1,iwiTrl,trialIwi);
        iwiId      = cat(1,iwiId,zeros(size(trialIwi,1),1));
        iwiTrlId   = cat(1,iwiTrlId,itrial * ones(size(trialIwi,1),1));
        nwoiIwi    = cat(1,nwoiIwi,(1:size(trialIwi,1))');
    end

end
%%%%%%%%%%%%%%%%%%%%%%%%%%%% extract inter-woi intervals %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
allTrl    = [allTrl; iwiTrl];
trl       = [allTrl zeros(size(allTrl,1),1)]; 
if ~isempty(iwiTrl)
    duration  = diff(iwiTrl,1,2);
    samples   = (iwiTrl - double(cfg.header.FirstTimeStamp))./cfg.header.TimeStampPerSample + 1;
    iwiData   = [iwiTrl round(samples) duration iwiId iwiTrlId nwoiIwi];
    iwiList   = array2table(iwiData,"VariableNames",...
        {'timeStart','timeEnd','sampleStart','sampleEnd','duration','woiID','trialID','nWoiTrial'});
    iwiList = addvars(iwiList,iwiLabel,'NewVariableNames','woiLabel');
    trlList = [trlList;iwiList]; % add inter-woi intervals
end

shortTimes            = trlList.duration < cfg.minDuration * 1e6;
trlList(shortTimes,:) = [];
trl(shortTimes,:)     = [];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% select specific wois %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if isfield(cfg,'woi')
    switch cfg.woi
        case {'preCue','cue','lick','headent','ici'}
            trl      = trl(strcmp(trlList.woiLabel,cfg.woi),:);
            trlList  = trlList(strcmp(trlList.woiLabel,cfg.woi),:);
            
        case 'event'
            trl      = trl(trlList.woiID > 2,:);
            trlList  = trlList(trlList.woiID > 2,:);
        case 'iwi'
            trl      = trl(trlList.woiID == 0,:);
            trlList  = trlList(trlList.woiID == 0,:);
    end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% select specific wois %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%




