function sessions = setSessions(ratIds)

% sessions = setSessions(ratIds)
%
% setSessions returns the default definition for early, transition, and
% late SIP sessions. It is mostly used by the sipConfig script, but it can
% always be called independently if needed. 
%
% Sergio Conde-Ocazionez, August 2024. 
% Neuromodulation & Behavior Laboratory
% Netherlands Institute for Neuroscience.

if nargin > 0
    sessions.ids = ratIds;
end

% Early sessions
sessions.early = {...
    1:5;...
    1:5;...
    1:4;... % because recodings from 5 is missing
    1:5;...
    1:5;...
    1:5;...
    1:5;...
    1:2;... % because escalated very early
    1:5;...
    [1 4];... % because recodings from 2 and 3 are missing
    1:5;...
    2:5;... % because recodings from 1 is missing
    1:5;...
    1:5;...
    1:5;...
    1:5;...
    };


% Transition sessions
sessions.transition = {...
    13:14;... % because these are the only recorded days
    13:14;... % because these are the only recorded days
    13:15;... % because these are the only recorded days
    13:15;... % because these are the only recorded days
    12:16;...
    9:13;...
    10:14;...
    4:8;... % because escalated very early
    11:15;...
    [10,11,13,15,16];... % because recodings from 12 and 14 are missing
    10:14;...
    10:14;...
    10:14;...
    10:14;...
    10:14;...
    10:14;...
};

% Late sessions

for irat = 1:16
    sessions.late{irat,1} = 23:25;
end
sessions.late{1} = [19 20]; % because these are the only recorded days
sessions.late{2} = [21 22]; % because these are the only recorded days
sessions.late{3} = 18:20; % because only 20 days of SIP
sessions.late{4} = 18:20; % because only 20 days of SIP
sessions.late{16} = [21 24]; % because 22 missing and 23,25 outliers